### ISSUE TITLE
What is token in server lookup and mass report 

### ISSUE THREAD

**Issue by Bhavy11111** [logicguy1/The-all-in-one-discord-tool#18]
What should I enter in TOKEN section in mass report and server lookup and mass report ?

**Comment by logicguy1** [comment]
Your token

**Comment by ghost** [comment]
Use an alt. This owner will prob take ur token

**Comment by logicguy1** [comment]
Who are you referring to as "this owner"?

**Comment by ghost** [comment]
you because kinda sus

**Comment by logicguy1** [comment]
Lmao, wym? Whats sus bout it

**Comment by ghost** [comment]
> Lmao, wym? Whats sus bout it 

Could be a logger

**Comment by logicguy1** [comment]
Its open source, read it lmao
