### ISSUE TITLE
I don't know why it's giving this error when trying to start

### ISSUE THREAD

**Issue by mbappedr0** [logicguy1/The-all-in-one-discord-tool#20]
i'm trying to start the boot but it doesn't work at all, i don't know if i did something wrong or if the bot is not working anymore

Checking internal version with servers
Module requests not installed, to install run 'python -m pip install requests'
Press enter to exit

it's giving this error

**Comment by logicguy1** [comment]
Did you try Reading the error?

**Comment by mbappedr0** [comment]
> Did you try Reading the error?

Sorry, before it wasn't working even though I installed it, I must have run it wrong
